name: dbt Commands

on: [push]

jobs:
  dbt-runner:
    runs-on: ubuntu-latest
    steps:
      - name: install dbt
        run: pip install dbt-snowflake
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
